drop table if exists bookmakrs;

create table bookmarks (
    id INTEGER primary key generated by deafult as identity,
    title text NOT NULL,
    link text NOT NULL,
    abstract text,
    rating INTEGER NOT NULL
);

insert into bookmarks (title, link, abstract, rating)
values
    ('Google', 'https://www.google.com/', 'search', 5),
    ('Bing', 'https://www.bing.com/', 'less used search', 4),
    ('YouTube', 'https://www.youtube.com/', 'videos', 5),
    ('Walmart', 'https://www.walmart.com/', 'Shop', 4),
    ('Best Buy', 'https://www.bestbuy.com/', 'electronics', 4),
    ('Gucci', 'https://www.gucci.com/us/en/', 'expensive', 3),
    ('Ross', 'https://www.rossstores.com/', 'cheap', 5),
    ('Yankee Candle', 'https://www.yankeecandle.com/', 'candles', 4),
    ('St. Louis Blues', 'https://www.nhl.com/blues', 'Hockey', 5),
    ('PGA', 'https://www.pgatour.com/', 'Golf', 5);